### ISSUE TITLE
Sweep: Please check the code for following Sequence Flow and Entity Relationship and ensure application backend and frontend is running successfully

### ISSUE THREAD

**Issue by iconixgroups** [iconixgroups/Manage-X#8]
### Details
Manage X application after installing is not performing any function. Please check the below sequence is adapted inside the Manage X Application and verify Entity Relationship which is also given below for reference; After installing based on the Installation instructions app should function smoothly using Backend and Frontend. I have seen only one index.html file for landing page and to use the application i saw vue file but there were no other pages of the app with HTML and CSS by using shadcn ui libraries.
Please ensure the Manage X Application has following sequence flow for the Manage X software application based on the provided details:
**1. Landing Page**
- [ ] User selects "Free Trial" or "Paid Subscription" option
**2. Sign Up (Free Trial) / Payment (Paid)**
- [ ] User registers with email address
- [ ] Email verification link sent
**3. Profile Setup**
- [ ] User provides details like name, company etc.
**4. Workspace Creation**
- [ ] User creates new workspace
- [ ] Provides workspace name, logo, color code
**5. Project Creation**
- [ ] User creates new project within workspace
- [ ] Provides project details like name, logo, categories, start/end dates etc.
**6. Task Management**
- [ ] User views task tree list
- [ ] Adds, edits, deletes tasks
- [ ] Tasks have statuses, assignments, dates etc.
**7. Project Progress**
- [ ] Dashboard shows graphs and trends for task progress
- [ ] Activity log tracks user actions chronologically
**8. Settings**
- [ ] User can update details of workspaces, projects, profile
- [ ] Admins have additional controls and activity logs
**9. Notifications**
- [ ] Real-time notifications on task changes, updates etc.
The core flow focuses on workspaces, projects and tasks as key entities. Additional capabilities like reporting, access controls, notifications and settings complement the main workflow.
Please ensure the entity relationship diagram for the Manage X software application:
              +-----------------+
              |     Users                |
              +-----------------+
              | - User ID              |
              | - Email                 | 
              | - Password *       |
              | - Name                | 
              | - Contact info     |
              | - Company          |
              +--------+--------+
                       |
                       |
                       |
+----------------------+-----------------------+
|                                                                                | 
|                  Workspaces                                         |    
|                                                                                |
+------------------------------------------------+
| - Workspace ID                                                     |
| - Name                                                                   |
| - Logo                                                                     | 
| - Color code                                                           |
| - Workspace Owner                                               |     
+------------------------------------------------+
                       |
                       | 
                       |
             +-------------------+             
             |     Projects                |
             +-------------------+
             | - Project ID               |
             | - Workspace ID        |
             | - Name                      |
             | - Logo                       |
             | - Color code             | 
             | - Start date               |
             | - End date                 |
             | - Scope of Works     |     
             | - Project Admin        |
             | - Project Members   |        
             +--------+----------+
                      |
                      |
                      |          
+---------------------+---------------+
|                                                                 |
|                Tasks                                       |
|                                                                 |  
+--------------------------------------+
| - Task ID                                                 |
| - Project ID                                             | 
| - Task Name                                           |
| - Task Description                                  |
| - Status                                                   |
| - Assigned to                                          |
| - Start date                                             |
| - End date                                               |
| - Category                                              |
| - Tags                                                      |
| - Priority                                                  |
| - File Attachment                                   |
| - Comments                                           |
+--------------------------------------+

* Password stored as secured hash 

The key entities are:

- Users - Stores registered user information
- Workspaces - Represents groups of projects  
- Projects - Actual work efforts inside a workspace 
- Tasks - Activities to be completed under a project

Relationships:

- Users can have multiple Workspaces 
- Workspaces contain multiple Projects
- Projects contain multiple Users 
- Projects contain multiple Tasks

<details open>
<summary>Checklist</summary>

- [X] Create `public/js/pages/LandingPage.vue` ✓ https://github.com/iconixgroups/Manage-X/commit/decaf173465f57f2ddd272fde6455d0da16c30a4 [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/LandingPage.vue)
- [X] Running GitHub Actions for `public/js/pages/LandingPage.vue` ✓  [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/LandingPage.vue)
- [X] Create `public/js/pages/SignUpPage.vue` ✓ https://github.com/iconixgroups/Manage-X/commit/120cff3a826a4986d1378477c40c1a70faf77d0a [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/SignUpPage.vue)
- [X] Running GitHub Actions for `public/js/pages/SignUpPage.vue` ✓  [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/SignUpPage.vue)
- [X] Create `public/js/pages/ProfileSetupPage.vue` ✓ https://github.com/iconixgroups/Manage-X/commit/3ab18d360c7742a8836ba57c7570d00af874f2a3 [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/ProfileSetupPage.vue)
- [X] Running GitHub Actions for `public/js/pages/ProfileSetupPage.vue` ✓  [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/ProfileSetupPage.vue)
- [X] Create `public/js/pages/WorkspaceCreationPage.vue` ✓ https://github.com/iconixgroups/Manage-X/commit/78ea05a57567313c28c53c1a07015a39be0e9aaf [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/WorkspaceCreationPage.vue)
- [X] Running GitHub Actions for `public/js/pages/WorkspaceCreationPage.vue` ✓  [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/WorkspaceCreationPage.vue)
- [X] Create `public/js/pages/ProjectCreationPage.vue` ✓ https://github.com/iconixgroups/Manage-X/commit/7995b4fbbc890f4a0811580e17a630655265abda [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/ProjectCreationPage.vue)
- [X] Running GitHub Actions for `public/js/pages/ProjectCreationPage.vue` ✓  [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/ProjectCreationPage.vue)
- [X] Create `public/js/pages/TaskManagementPage.vue` ✓ https://github.com/iconixgroups/Manage-X/commit/75143801100d909c378491f3b2af6de14f090632 [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/TaskManagementPage.vue)
- [X] Running GitHub Actions for `public/js/pages/TaskManagementPage.vue` ✓  [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/TaskManagementPage.vue)
- [X] Create `public/js/pages/ProjectProgressPage.vue` ✓ https://github.com/iconixgroups/Manage-X/commit/010226b0baea406e2259c1fc9aad4ce728dff23a [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/ProjectProgressPage.vue)
- [X] Running GitHub Actions for `public/js/pages/ProjectProgressPage.vue` ✓  [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/ProjectProgressPage.vue)
- [X] Create `public/js/pages/SettingsPage.vue` ✓ https://github.com/iconixgroups/Manage-X/commit/8fefc3b463329be1d1b353c293af740b50b9390d [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/SettingsPage.vue)
- [X] Running GitHub Actions for `public/js/pages/SettingsPage.vue` ✓  [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/SettingsPage.vue)
- [X] Create `public/js/pages/NotificationsPage.vue` ✓ https://github.com/iconixgroups/Manage-X/commit/e37e0b5ded8ad869b30c8c5c2e7df1cfec0245e4 [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/NotificationsPage.vue)
- [X] Running GitHub Actions for `public/js/pages/NotificationsPage.vue` ✓  [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/pages/NotificationsPage.vue)
- [X] Modify `controllers/projectController.js` ✓ https://github.com/iconixgroups/Manage-X/commit/48e5fcd16d33eb613c411dea404a56b5da249de9 [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/controllers/projectController.js#L7-L122)
- [X] Running GitHub Actions for `controllers/projectController.js` ✓  [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/controllers/projectController.js#L7-L122)
- [ ] Modify `public/js/plugins/axios.js` ▶  [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/plugins/axios.js)
- [ ] Running GitHub Actions for `public/js/plugins/axios.js` ▶  [Edit](https://github.com/iconixgroups/Manage-X/edit/sweep/please_check_the_code_for_following_sequ/public/js/plugins/axios.js)
</details>
